config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#splash'
  resources :categories do
    resources :purchases, only: [:new, :show]
  end
  resources :purchases, except: [:new, :show, :index]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # Associations
  belongs_to :user
  has_and_belongs_to_many :purchases

  # Methods

  # Validations
  validates :name, presence: true
  validates :icon, presence: true

  # Callbacks
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories

  # Methods

  # Validations
  validates :name, presence: true
  validates :amount, presence: true
  validates :categories, presence: true

  # Callbacks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :categories
  has_many :purchases

  # Attributes
  attribute :name, :string

  # Callbacks

  # Validations
  validates :name, presence: true

  # Mehtods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      # Customize the redirection path for the User model
      categories_path
      categories_path
    else
      super # Use Devise's default behavior for other resources
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories.includes(:purchases)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @purchases = @category.purchases.order(created_at: :desc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        handle_uploaded_icon_file if category_params[:icon].present?
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        handle_uploaded_icon_file if category_params[:icon].present?
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def handle_uploaded_icon_file
    uploaded_file = category_params[:icon]
    file_path = Rails.root.join('public', 'uploads', uploaded_file.original_filename)

    File.binwrite(file_path, uploaded_file.read)

    @category.update(icon: File.join('/uploads', uploaded_file.original_filename))
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_purchase, only: %i[show edit update destroy]

  # GET /purchases or /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1 or /purchases/1.json
  def show; end

  # GET /purchases/new
  def new
    @attributes = []
    @purchase = Purchase.new
    @attributes << @purchase
    @categories = current_user.categories
    @attributes << @categories
  end

  # GET /purchases/1/edit
  def edit
    @attributes = []
    @attributes << @purchase
    @categories = current_user.categories
    @attributes << @categories
  end

  # POST /purchases or /purchases.json
  def create
    @attributes = []
    @purchase = Purchase.new(purchase_params)
    @purchase.author = current_user
    category_id = params[:purchase][:category_id]
    if category_id.present?
      category = Category.find(category_id)
      @purchase.categories << category
    end
    @attributes << @purchase
    @categories = current_user.categories
    @attributes << @categories

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to category_url(@purchase.categories[0]), notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to purchase_url(@purchase), notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def purchase_params
    params.require(:purchase).permit(:name, :amount)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def splash; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="category-item drop-shadow-md bg-white flex justify-between w-full p-3 rounded">
    <% if category.icon.present? %>
        <%= image_tag category.icon, alt: category.name, class: 'w-16 rounded' %>
    <% end %>

  <div class="w-10/12 width-salim flex flex-col justify-between mt-5" style="width: 80%;">
    <div class="flex justify-between border-b-1">
    <p class="item-title-color">
      <strong><%= category.name %></strong>
    </p>
    <p class="self-center amount-color">
      <strong>Total: $<%= category.purchases.sum(:amount) %></strong>
    </p>
    </div>
    
    <p class="date-color text-xs">
    <span><%= category.created_at.strftime('%d %b %Y') %></span>
    </p>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: 'mt-10 flex flex-col gap-5 ms-4') do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon, id: 'icon_upload' %>
  </div>

  <div>
    <%= form.submit "Save", class: 'p-3 px-5 green-btn rounded hover:bg-green-600' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="navigation py-6 px-3 blue-nav-white-text">
      <ul class="flex justify-between items-center">
        <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(@category), class: 'nav-link' %></li>
        <h2><strong>Editing category</strong></h2>
        <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
      </ul>
    </div>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<div class="flex flex-col h-screen justify-between">
  <div>
    <div class="navigation py-6 px-3 blue-nav-white-text">
      <ul class="flex justify-between items-center">
        <li class="w-10">
          <%= link_to image_tag('backarrow.png', alt: 'Back'), root_path, class: 'nav-link' %>
        </li>
        <h2><strong>Categories</strong></h2>
        <li>
          <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
        </li>
      </ul>
    </div>

    <section class="px-5">
      <p style="color: green"><%= notice %></p>

      <div id="categories">
        <% @categories.each do |category| %>
          <a href="<%= category_path(category) %>" class="m-1">
            <%= render category %>
          </a>
        <% end %>
      </div>
    </section>
  </div>

  <section class="text-center mt-4">
    <%= link_to new_category_path do %>
      <div class="w-full green-btn flex">
        <button class="p-2 py-4 m-4 text-lg w-full border-2 green-btn rounded hover:bg-green-600 focus:outline-none focus:bg-green-600">
          <strong>Add a New Category</strong>
        </button>
      </div>
    <% end %>
  </section>
</div>

app/views/categories/new.html.erb
<div class="navigation py-6 px-3 blue-nav-white-text">
  <ul class="flex justify-between items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
    <h2><strong>New category</strong></h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<div class="flex flex-col h-screen justify-between">
  <div>
    <div class="navigation py-6 px-3 blue-nav-white-text">
      <ul class="flex justify-between items-center">
        <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
        <h2><strong><%= @category.name %></strong></h2>
        <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
      </ul>
    </div>
    <p style="color: green"><%= notice %></p>

    <%= render @category %>
    <section class="px-5">
      <div id="purchases">
        <% @purchases.each do |purchase| %>
          <a href="<%= category_purchase_path(@category, purchase) %>" class="m-1">
          <%= render "purchases/purchase", purchase: purchase %>
          </a>
        <% end %>
      </div>
    </section>
  </div>

  <section class="flex flex-col space-y-2 p-5">
      <a href="<%= new_category_purchase_path(@category) %>" class="">
        <button data-testid="new-purchase-button" class="drop-shadow-md p-3 w-full green-btn text-white rounded-md hover:bg-green-600 focus:outline-none focus:bg-green-600">
          New purchase
        </button>
      </a>

      <%= link_to edit_category_path(@category) do %>
        <button data-testid="edit-category-button" class="drop-shadow-md p-3 orange-btn bg-white w-full rounded hover:bg-orange-600">Edit category</button>
      <% end %>

      <%= button_to "Delete category", @category, method: :delete, data: { confirm: 'Are you sure?' }, class: "drop-shadow-md w-full p-3 red-btn text-white rounded-md hover:bg-red-600 focus:outline-none focus:bg-red-600" %>
    </section>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_with(model: attributes[0], local: true, class: 'mt-10 flex flex-col gap-5 ms-4') do |form| %>
  <% if attributes[0].errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attributes[0].errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% attributes[0].errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :category, style: "display: block", class: 'invisible' %>
    <%= form.collection_select :category_id, attributes[1], :id, :name, { prompt: 'Choose category.....' }%>
  </div>

  <div>
    <%= form.submit "Save", class: 'p-3 px-5 green-btn rounded hover:bg-green-600' %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<div id="<%= dom_id purchase %>" class="drop-shadow-md bg-white flex w-full p-3 rounded justify-between">
<div>
  <p>
    <strong><%= purchase.name %></strong>
  </p>

  <p class="date-color text-xs">
    <span><%= purchase.created_at.strftime('%d %b %Y') %></span>
  </p>
</div>
  
  <p class="amount-color">
    $<%= purchase.amount %>
  </p>

</div>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", attributes: @attributes %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Purchases</h1>

<div id="purchases">
  <% @purchases.each do |purchase| %>
    <%= render purchase %>
    <p>
      <%= link_to "Show this purchase", purchase %>
    </p>
  <% end %>
</div>

<%#= link_to "New purchase", new_purchase_path %>

app/views/purchases/new.html.erb
<div class="navigation py-6 px-3 blue-nav-white-text">
  <ul class="flex justify-between items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
    <h2><strong>New purchase</strong></h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>

<%= render "form", attributes: @attributes %>

app/views/purchases/show.html.erb
<div class="navigation py-6 px-3 blue-nav-white-text">
  <ul class="flex justify-between items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(@purchase.categories[0]), class: 'nav-link' %></li>
    <h2><strong>Show purchase</strong></h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>
<p style="color: green"><%= notice %></p>

<div class="flex flex-col bg-white p-5 drop-shadow-md">
  <p class="flex justify-between py-2">
    <span><strong>Name:</strong></span>
    <span><%= @purchase.name %></span>
  </p>
  <p class="border-y-4 py-2 flex justify-between">
    <span><strong>Amount:</strong></span>
    <span>$<%= @purchase.amount %></span>
  </p>
  <p class="border-b-4 py-2 flex justify-between">
    <span><strong>Categories:</strong></span>
    <span><%= @purchase.categories[0].name %></span>
  </p>
  <p class="py-2 flex justify-between">
    <span><strong>Created at:</strong></span>
    <span><%= @purchase.created_at %></span>
  </p>
</div>

<div>
  <%= button_to "Delete", @purchase, method: :delete, class: "mt-5 ms-5 p-3 px-5 red-btn text-white rounded-md hover:bg-red-600 focus:outline-none focus:bg-red-600 drop-shadow-md" %>
</div>

app/views/static_pages/splash.html.erb
<div class="flex flex-col justify-between h-screen items-center">
  <p class="text-center p-3 blue-btn w-full">Welcome!</br>to my awesome app :)</p>
  <h1 class="text-4xl font-extrabold blue animate-scale">
    Budget Monitor
  </h1>
  <div class="w-full">
    <% if user_signed_in? %>
      <div>
        <a href="<%= categories_path %>" class="w-full">
          <button class="blue-btn w-full p-4">Start Monitoring!</button>
        </a>
      </div>
    <% else %>
      <div class="flex">
        <a href="/users/sign_in" class="w-1/2">
          <button class="blue-btn w-full p-4 border-e-2">Sign in</button>
        </a>
        <a href="/users/sign_up" class="w-1/2">
          <button class="blue-btn w-full p-4 border-s-2">Sign up</button>
        </a>
      </div>
    <% end %>
  </div>
</div>